# This workflow uses Flyway Hub to test the Flyway database migrations in the 'migrations' path(s).
#
# The workflow will run automatically against all pull requests that modify files under 'migrations'.
#
# It will also run on all pushes to 'dev' that modify files under 'migrations'.
#
# In order to use this workflow you will need to create a Github Actions secret called
# FLYWAY_HUB_ACCESS_TOKEN containing a valid Flyway Hub API access token.
#
name: Database Migration Tests with Flyway

on:
  push:
    branches:
    - 'dev'
    paths:
      - 'migrations/**'
  pull_request:
    paths:
    - 'migrations/**'
  workflow_dispatch: {}

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v2
      - name: Test migrations on Flyway Hub
        uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: service-api
          engine: postgres-13
          migrationDirs: migrations 
          flywayConfPath: migrations/flyway.conf  
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
